apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: araba-degerleme
type: Opaque
stringData:
  # OPENAI_API_KEY değerini gerçek key ile değiştirin
  OPENAI_API_KEY: "BURAYA_OPENAI_API_KEY_YAZIN"
  JWT_SECRET_KEY: "gizli_jwt_anahtari_degistir_123"
